import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const watch = process.argv[2] === "watch";
const debug = watch || process.argv[2] === "develop";

const PLUGIN_DIR =
  "/Users/mattobrien/Obsidian Main Vault/ObsidianVault/.obsidian/plugins/augment-terminal";

// In watch mode, output directly to the plugin dir so Obsidian hot-reload
// picks up changes immediately. Build mode outputs to repo root (committed).
const outfile = watch ? `${PLUGIN_DIR}/main.js` : "main.js";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  loader: { ".css": "text" },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: debug ? "inline" : false,
  treeShaking: true,
  outfile,
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  process.exit(0);
}
